### ISSUE TITLE
WebPoint: Document the interface between Sharepoint and GeoMapFish

### ISSUE THREAD

**Issue by ralphschulerSZ** [ralphschulerSZ/WebPoint#29]

**Comment by eleu** [comment]
Issue title: WebPoint: Document the interface between Sharepoint and GeoMapFish (please change the title, as I cannot do that).

The Sharepoint application in WebPoint is using some ressources for the GIS part from GeoMapFish. In order to maintain the API compability and to be able to test if all works well on the GeoMapFish side, we have to know what ressources Sharepoint uses from GeoMapFish.

What URL's of GeoMapFish are accessed directly\* from Sharepoint?

I guess this is:
- Some javascript files (which ones in detail?-> give the URL's)
- Some WFS requests (which base URL?)
- Some Mapfish Protocol requests (which base URL?)
- Tiles?

To complete the documentation: What other external ressources are loaded?
- f.e. tiles directly from Swisstopo?

*directly = the ressources which are "hardcoded" in Sharepoint. This would be f.e. a html file from GeoMapFish which is loaded from Sharepoint, but not the javascript files that are referenced in the (GeoMapFish)-HTML.
